name: Mocha tests

on:
  push:
    branches: [ develop ]
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warn'
      tags:
        description: 'Test scenario tags' 

jobs:
  mochaTest:

    runs-on: ubuntu-latest

    steps:
      - name: Any Name Bash Test Step
        shell: bash
        run: |
          echo "Log level: ${{ github.event.inputs.logLevel }}"
          echo "Tags: ${{ github.event.inputs.tags }}" 
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - name: Install dependencies
        run: npm ci
      - name: Run the tests
        run: npm run test:mocha_allure2