name: Run Mocha with Allure report

on:
  push:
  workflow_dispatch:
    inputs:
      test_env:
        description: 'Environment for testing'
        required: true
        default: 'test'

env:
  TEST_ENV: "${{ inputs.test_env != '' && inputs.test_env || 'test' }}"

jobs:
  mochaTest:
    name: Testing mocha and Allure
    runs-on: ubuntu-latest
    steps:
      - name: First step
        id: step1
        run: echo "Just fine"

      - name: Set output
        if: ${{ steps.step1.outcome == 'success' }}
        run: echo THIS_IS_SUCCESS
  
  otherJob:
    name: Other
    needs: mochaTest
    # if: ${{ contains(needs.mochaTest.result, 'THIS_IS_SUCCESS') }}
    runs-on: ubuntu-latest
    steps:
      - name: Print env vars
        run: echo "${{ needs.mochaTest.result }}"