name: Run Mocha with Allure report

on:
  push:
    branches: [ develop ]

  workflow_dispatch:
    inputs:
      test_env:
        description: 'Environment for testing'
        required: true
        default: 'test'

env:
  TEST_ENV: "${{ inputs.test_env != '' && inputs.test_env || 'test' }}"

jobs:
  mochaTest:
    name: Testing mocha and Allure
    runs-on: ubuntu-latest
    environment: develop
    steps:
      - name: Print env vars
        shell: bash
        run: |
          echo "Env variable from repository: '${{ vars.LOG_LEVEL }}'"
          echo "Test env is: '$TEST_ENV'"
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - name: Install dependencies
        run: npm ci
      - name: Run the tests
        run: npm run test:mocha_allure2
        continue-on-error: true
      - name: Publish pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./allure-report
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          commit_message: 'Committing the report for ${{ github.event.head_commit.message }}'