name: Run Mocha with Allure report

on:
  push:
  workflow_dispatch:
    inputs:
      test_env:
        description: 'Environment for testing'
        required: true
        default: 'test'

env:
  TEST_ENV: "${{ inputs.test_env != '' && inputs.test_env || 'test' }}"
  STEP_FLAG: false

jobs:
  mochaTest:
    name: Testing mocha and Allure
    runs-on: ubuntu-latest
    steps:
      - name: First step
        id: step1
        run: echo "Just fine"

      - name: Set output
        if: ${{ steps.step1.outcome == 'success' }}
        run: echo "STEP_FLAG=true" >> $GITHUB_ENV
  
  otherJob:
    name: Other
    needs: mochaTest
    if: env.STEP_FLAG == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Print env vars
        run: echo "ASDASDASDASDASD"